/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.18.1)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Google.Cloud.PubSub.Compression.Thrift
{

  public partial class PhoneBook : TBase
  {
    private List<global::Google.Cloud.PubSub.Compression.Thrift.Person> _people;

    public List<global::Google.Cloud.PubSub.Compression.Thrift.Person> People
    {
      get
      {
        return _people;
      }
      set
      {
        __isset.people = true;
        this._people = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool people;
    }

    public PhoneBook()
    {
    }

    public PhoneBook DeepCopy()
    {
      var tmp19 = new PhoneBook();
      if((People != null) && __isset.people)
      {
        tmp19.People = this.People.DeepCopy();
      }
      tmp19.__isset.people = this.__isset.people;
      return tmp19;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  var _list20 = await iprot.ReadListBeginAsync(cancellationToken);
                  People = new List<global::Google.Cloud.PubSub.Compression.Thrift.Person>(_list20.Count);
                  for(int _i21 = 0; _i21 < _list20.Count; ++_i21)
                  {
                    global::Google.Cloud.PubSub.Compression.Thrift.Person _elem22;
                    _elem22 = new global::Google.Cloud.PubSub.Compression.Thrift.Person();
                    await _elem22.ReadAsync(iprot, cancellationToken);
                    People.Add(_elem22);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp23 = new TStruct("PhoneBook");
        await oprot.WriteStructBeginAsync(tmp23, cancellationToken);
        var tmp24 = new TField();
        if((People != null) && __isset.people)
        {
          tmp24.Name = "people";
          tmp24.Type = TType.List;
          tmp24.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp24, cancellationToken);
          await oprot.WriteListBeginAsync(new TList(TType.Struct, People.Count), cancellationToken);
          foreach (global::Google.Cloud.PubSub.Compression.Thrift.Person _iter25 in People)
          {
            await _iter25.WriteAsync(oprot, cancellationToken);
          }
          await oprot.WriteListEndAsync(cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is PhoneBook other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.people == other.__isset.people) && ((!__isset.people) || (TCollections.Equals(People, other.People))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((People != null) && __isset.people)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(People);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp26 = new StringBuilder("PhoneBook(");
      int tmp27 = 0;
      if((People != null) && __isset.people)
      {
        if(0 < tmp27++) { tmp26.Append(", "); }
        tmp26.Append("People: ");
        People.ToString(tmp26);
      }
      tmp26.Append(')');
      return tmp26.ToString();
    }
  }

}
